
import { Car } from './types';

export const CARS: Car[] = [
  {
    id: 'lc-300',
    name: 'Land Cruiser 300',
    brand: 'Toyota',
    type: 'SUV',
    pricePerDay: 30000,
    image: 'https://i.ibb.co/1JmXL24x/Untitled-design-13.png',
    transmission: 'Automatic',
    seats: 7,
    fuel: 'Diesel',
    rating: 5.0,
    reviewCount: 124,
    description: 'The king of all terrains. Unmatched reliability meets legendary capability for long-distance travel across Pakistan.',
    isPopular: true
  },
  {
    id: 'toyota-revo-2024',
    name: 'Hilux Revo',
    brand: 'Toyota',
    type: 'SUV',
    pricePerDay: 16000,
    image: 'https://i.ibb.co/qMpz2SbP/Untitled-design-26.png',
    transmission: 'Automatic',
    seats: 5,
    fuel: 'Diesel',
    rating: 4.8,
    reviewCount: 52,
    description: 'The Toyota Hilux Revo is the ultimate utility vehicle, blending legendary durability with modern comfort. Built to handle the toughest roads while providing a premium cabin experience.',
    isPopular: true
  },
  {
    id: 'haval-h6-2024',
    name: 'H6',
    brand: 'Haval',
    type: 'SUV',
    pricePerDay: 17000,
    image: 'https://i.ibb.co/FLZqP3z2/Untitled-design-25.png',
    transmission: 'Automatic',
    seats: 5,
    fuel: 'Petrol',
    rating: 4.7,
    reviewCount: 34,
    description: 'The Haval H6 is a masterpiece of modern engineering, combining sophisticated tech with a bold, futuristic design. A premium choice for those who value innovation and luxury on the move.',
    isPopular: true
  },
  {
    id: 'toyota-coaster-2024',
    name: 'Coaster',
    brand: 'Toyota',
    type: 'SUV',
    pricePerDay: 0,
    image: 'https://i.ibb.co/KpVPGKjF/Untitled-design-24.png',
    transmission: 'Manual',
    seats: 22,
    fuel: 'Diesel',
    rating: 4.7,
    reviewCount: 22,
    description: 'The Toyota Coaster is the definitive choice for large group transport. Offering a spacious interior and advanced safety features, it ensures a smooth and comfortable journey for up to 22 passengers.',
    isPopular: true
  },
  {
    id: 'toyota-fortuner-2024',
    name: 'Fortuner',
    brand: 'Toyota',
    type: 'SUV',
    pricePerDay: 20000,
    image: 'https://i.ibb.co/Cp5VjWbw/Untitled-design-23.png',
    transmission: 'Automatic',
    seats: 7,
    fuel: 'Diesel',
    rating: 4.8,
    reviewCount: 76,
    description: 'The Toyota Fortuner is the ultimate symbol of power and prestige. A robust SUV designed for both off-road dominance and urban luxury.',
    isPopular: true
  },
  {
    id: 'toyota-hiace-2024',
    name: 'Hiace',
    brand: 'Toyota',
    type: 'SUV',
    pricePerDay: 16000,
    image: 'https://i.ibb.co/wNjNSWmH/Untitled-design-22.png',
    transmission: 'Automatic',
    seats: 12,
    fuel: 'Diesel',
    rating: 4.6,
    reviewCount: 38,
    description: 'The Toyota Hiace is the global benchmark for passenger transport. Unrivaled space, comfort, and reliability for large groups and business travel.',
    isPopular: true
  },
  {
    id: 'toyota-prado-2024',
    name: 'Prado',
    brand: 'Toyota',
    type: 'SUV',
    pricePerDay: 25000,
    image: 'https://i.ibb.co/Kcx4wKdc/Untitled-design-19.png',
    transmission: 'Automatic',
    seats: 7,
    fuel: 'Diesel',
    rating: 4.9,
    reviewCount: 85,
    description: 'The legendary Prado offers the perfect balance of rugged capability and refined luxury. Built to conquer every terrain in style.',
    isPopular: true
  },
  {
    id: 'glory-580-pro-2024',
    name: 'Glory 580 Pro',
    brand: 'DFSK',
    type: 'SUV',
    pricePerDay: 18000,
    image: 'https://i.ibb.co/gLpYYZrY/Untitled-design-21.png',
    transmission: 'Automatic',
    seats: 7,
    fuel: 'Petrol',
    rating: 4.5,
    reviewCount: 42,
    description: 'The DFSK Glory 580 Pro is a versatile and spacious 7-seater SUV. With its modern features and comfortable cabin, it is designed for memorable family adventures.',
    isPopular: true
  },
  {
    id: 'honda-city-2024',
    name: 'City',
    brand: 'Honda',
    type: 'Sedan',
    pricePerDay: 8000,
    image: 'https://i.ibb.co/BHBZQbx0/Untitled-design-20.png',
    transmission: 'Automatic',
    seats: 5,
    fuel: 'Petrol',
    rating: 4.7,
    reviewCount: 54,
    description: 'The Honda City is a perfect blend of style, comfort, and performance. Ideal for city commutes and long highway drives with its efficient engine and premium interior.',
    isPopular: true
  },
  {
    id: 'kia-sportage-2024',
    name: 'Sportage',
    brand: 'Kia',
    type: 'SUV',
    pricePerDay: 14000,
    image: 'https://i.ibb.co/zHtVNFwX/Untitled-design-18.png',
    transmission: 'Automatic',
    seats: 5,
    fuel: 'Petrol',
    rating: 4.8,
    reviewCount: 92,
    description: 'The Kia Sportage offers a striking design, a premium interior, and a smooth driving experience. Perfect for style-conscious urban explorers.',
    isPopular: true
  },
  {
    id: 'toyota-corolla-gli-2024',
    name: 'Corolla GLI',
    brand: 'Toyota',
    type: 'Sedan',
    pricePerDay: 6100,
    image: 'https://i.ibb.co/XkNb3gPh/Untitled-design-17.png',
    transmission: 'Automatic',
    seats: 5,
    fuel: 'Petrol',
    rating: 4.7,
    reviewCount: 61,
    description: 'The legendary Toyota Corolla GLI. Renowned for its durability, smooth ride, and timeless design. A trusted companion for every road.',
    isPopular: true
  },
  {
    id: 'audi-a6-2024',
    name: 'A6',
    brand: 'Audi',
    type: 'Luxury',
    pricePerDay: 40000,
    image: 'https://i.ibb.co/23St6CMD/Untitled-design-16.png',
    transmission: 'Automatic',
    seats: 5,
    fuel: 'Petrol',
    rating: 4.9,
    reviewCount: 72,
    description: 'The Audi A6 combines sophisticated design with cutting-edge technology. Experience the perfect blend of performance, comfort, and German engineering excellence.',
    isPopular: true
  },
  {
    id: 'toyota-yaris-2024',
    name: 'Yaris',
    brand: 'Toyota',
    type: 'Sedan',
    pricePerDay: 6000,
    image: 'https://i.ibb.co/XrMdwQB2/Untitled-design-15.png',
    transmission: 'Automatic',
    seats: 5,
    fuel: 'Petrol',
    rating: 4.6,
    reviewCount: 48,
    description: 'Efficiency meets reliability in a compact sedan. The Toyota Yaris is the perfect choice for navigating city streets with ease and style.',
    isPopular: true
  },
  {
    id: 'suzuki-wagonr-2024',
    name: 'Wagon R',
    brand: 'Suzuki',
    type: 'Hatchback',
    pricePerDay: 4000,
    image: 'https://i.ibb.co/d4jQ31N7/Untitled-design-14.png',
    transmission: 'Manual',
    seats: 5,
    fuel: 'Petrol',
    rating: 4.2,
    reviewCount: 35,
    description: 'The iconic tall-boy design. Suzuki Wagon R offers maximum interior space and excellent fuel economy for urban explorers.',
    isPopular: true
  },
  {
    id: 'suzuki-cultus-2024',
    name: 'Cultus',
    brand: 'Suzuki',
    type: 'Hatchback',
    pricePerDay: 4000,
    image: 'https://i.ibb.co/8Lrd4nSh/Untitled-design-12.png',
    transmission: 'Automatic',
    seats: 5,
    fuel: 'Petrol',
    rating: 4.3,
    reviewCount: 45,
    description: 'The most popular hatchback for city driving. Compact, fuel-efficient, and surprisingly spacious for daily urban commutes.',
    isPopular: true
  },
  {
    id: 'suzuki-apv-2024',
    name: 'APV',
    brand: 'Suzuki',
    type: 'SUV',
    pricePerDay: 7000,
    image: 'https://i.ibb.co/nqz6rLWb/7889.png',
    transmission: 'Automatic',
    seats: 8,
    fuel: 'Petrol',
    rating: 4.4,
    reviewCount: 29,
    description: 'The ultimate multi-purpose vehicle. Spacious 8-seater capacity making it the perfect choice for large group travels.',
    isPopular: true
  },
  {
    id: 'honda-civic-2021',
    name: 'Civic',
    brand: 'Honda',
    type: 'Sedan',
    pricePerDay: 8000,
    image: 'https://i.ibb.co/F46h3JTS/mlp-img-top-2021-civic.avif',
    transmission: 'Automatic',
    seats: 5,
    fuel: 'Petrol',
    rating: 4.8,
    reviewCount: 64,
    description: 'The Honda Civic redefined. Sleek design, fuel efficiency, and a comfortable ride for city and highway cruising.',
    isPopular: true
  },
  {
    id: 'mg-hs-2024',
    name: 'HS',
    brand: 'MG',
    type: 'SUV',
    pricePerDay: 14000,
    image: 'https://i.ibb.co/4RdRHyjS/hs-ice-configurator-pebble-black.webp',
    transmission: 'Automatic',
    seats: 5,
    fuel: 'Petrol',
    rating: 4.5,
    reviewCount: 38,
    description: 'The MG HS combines bold design with a premium, high-tech interior. Perfect for those who demand style and comfort on the road.',
    isPopular: true
  },
  {
    id: 'brv-2024',
    name: 'BR-V',
    brand: 'Honda',
    type: 'SUV',
    pricePerDay: 8000,
    image: 'https://i.ibb.co/M52p0SkX/1.png',
    transmission: 'Automatic',
    seats: 7,
    fuel: 'Petrol',
    rating: 4.6,
    reviewCount: 42,
    description: 'Spacious, versatile, and reliable. The Honda BR-V is the ultimate 7-seater choice for comfortable family journeys.',
    isPopular: true
  },
  {
    id: 'tucson-2025',
    name: 'Tucson 2025',
    brand: 'Hyundai',
    type: 'SUV',
    pricePerDay: 15000,
    image: 'https://i.ibb.co/S74k9sXs/mlp-img-top-2025-tucson.avif',
    transmission: 'Automatic',
    seats: 5,
    fuel: 'Petrol',
    rating: 4.7,
    reviewCount: 56,
    description: 'Modern elegance meets versatility. The 2025 Tucson offers a premium interior and smooth ride for urban and highway travel.',
    isPopular: true
  }
];

export const REVIEWS = [
  {
    id: 1,
    name: "Ali Khan",
    location: "Lahore, Pakistan",
    rating: 5,
    comment: "The Land Cruiser 300 was in pristine condition. Perfect for my family trip to the northern areas. The rental process with Safar Nama was seamless.",
    date: "Feb 2025"
  },
  {
    id: 2,
    name: "Fatima Zahra",
    location: "Karachi, Pakistan",
    rating: 5,
    comment: "Highly recommend Safar Nama for long road trips. Very efficient service and luxury experience.",
    date: "Jan 2025"
  },
  {
    id: 3,
    name: "Muhammad Usman",
    location: "Islamabad, Pakistan",
    rating: 4,
    comment: "Great experience renting the Tucson for a weekend drive. Safar Nama has a very professional staff and well-maintained fleet.",
    date: "Dec 2024"
  }
];
